# Generated by Django 6.0.5 on 2026-05-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_fees', models.IntegerField()),
                ('course_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
