# Generated by Django 6.0.5 on 2026-05-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.course'),
        ),
    ]
