# Generated by Django 6.1.1 on 2026-09-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsignup',
            name='password',
        ),
        migrations.AddField(
            model_name='patientsignup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
