# Generated by Django 6.1.1 on 2026-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_remove_patientsignup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsignup',
            name='password',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
    ]
