# Generated by Django 6.1.1 on 2026-09-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_patientsignup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsignup',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
